package com.unionpay.mobile.android.g;

import com.unionpay.mobile.android.i.d;
import com.unionpay.mobile.android.views.order.l;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;

public final class b {
    public static boolean aA = false;
    public static boolean aB = false;
    public static boolean ba = false;
    public static List<d> bb = null;
    public static boolean bl = false;
    public static boolean bm = false;
    public static boolean bn = false;
    public static boolean bo = false;
    public String A;
    public String B;
    public JSONObject C;
    public JSONArray D;
    public String E;
    public boolean F;
    public JSONObject G;
    public JSONArray H;
    public d I;
    public boolean J;
    public boolean K;
    public boolean L;
    public String M;
    public int N;
    public String O;
    public String P;
    public String Q;
    public String R;
    public String S;
    public JSONArray T;
    public boolean U;
    public String V;
    public String W;
    public JSONArray X;
    public JSONObject Y;
    public JSONObject Z;
    public String a;
    public boolean aC;
    public boolean aD;
    public boolean aE;
    public JSONObject aF;
    public String aG;
    public String aH;
    public String aI;
    public String aJ;
    public String aK;
    public String aL;
    public boolean aM;
    public int aN;
    public int aO;
    public int aP;
    public int aQ;
    public String aR;
    public String aS;
    public String aT;
    public JSONObject aU;
    public boolean aV;
    public String aW;
    public String aX;
    public String aY;
    public boolean aZ;
    public JSONObject aa;
    public List<c> ab;
    public JSONArray ac;
    public JSONArray ad;
    public String ae;
    public String af;
    public String ag;
    public int ah;
    public String ai;
    public String aj;
    public String ak;
    public JSONObject al;
    public JSONObject am;
    public String an;
    public int ao;
    public String ap;
    public String aq;
    public String ar;
    public String as;
    public String at;
    public JSONObject au;
    public JSONObject av;
    public boolean aw;
    public boolean ax;
    public boolean ay;
    public boolean az;
    public String b;
    public int bc;
    public int bd;
    public int be;
    public String bf;
    public String bg;
    public String bh;
    public String bi;
    public String bj;
    public String bk;
    public String bp;
    public String bq;
    public boolean br;
    public c bs;
    public String bt;
    public boolean c;
    public String d;
    public String e;
    public boolean f;
    public String g;
    public JSONArray h;
    public JSONObject i;
    public JSONObject j;
    public String k;
    public String l;
    public String m;
    public String n;
    public String o;
    public HashMap<String, String> p;
    public List<c> q;
    public String r;
    public String s;
    public JSONArray t;
    public String u;
    public JSONObject v;
    public JSONObject w;
    public JSONObject x;
    public String y;
    public JSONArray z;

    public b() {
        this.a = "1.9";
        this.b = "";
        this.c = true;
        this.d = "";
        this.e = "";
        this.f = false;
        this.g = null;
        this.h = null;
        this.i = null;
        this.j = null;
        this.k = null;
        this.l = null;
        this.m = null;
        this.n = "";
        this.o = "";
        this.p = null;
        this.q = null;
        this.r = null;
        this.s = null;
        this.t = null;
        this.u = null;
        this.v = null;
        this.w = null;
        this.x = null;
        this.y = null;
        this.z = null;
        this.A = "";
        this.B = "";
        this.C = null;
        this.D = null;
        this.E = "";
        this.F = false;
        this.G = null;
        this.H = null;
        this.I = null;
        this.J = false;
        this.K = false;
        this.L = false;
        this.M = "0";
        this.N = 0;
        this.O = "";
        this.P = null;
        this.Q = null;
        this.R = "";
        this.S = "";
        this.T = null;
        this.U = false;
        this.V = null;
        this.W = null;
        this.X = null;
        this.Y = null;
        this.Z = null;
        this.aa = null;
        this.ab = null;
        this.ac = null;
        this.ad = null;
        this.ae = null;
        this.af = "";
        this.ag = "";
        this.ah = 0;
        this.ai = "";
        this.aj = "";
        this.ak = "";
        this.al = null;
        this.am = null;
        this.an = null;
        this.ao = 0;
        this.ap = "";
        this.aq = null;
        this.ar = null;
        this.as = null;
        this.at = null;
        this.au = null;
        this.av = null;
        this.aw = false;
        this.ax = false;
        this.ay = false;
        this.az = false;
        this.aC = false;
        this.aD = false;
        this.aE = false;
        this.aF = null;
        this.aG = null;
        this.aH = null;
        this.aI = null;
        this.aJ = null;
        this.aK = null;
        this.aL = null;
        this.aM = false;
        this.aN = 0;
        this.aO = 0;
        this.aP = l.a.intValue();
        this.aQ = l.b.intValue();
        this.aR = null;
        this.aS = null;
        this.aT = null;
        this.aU = null;
        this.aV = false;
        this.aW = null;
        this.aX = null;
        this.aY = null;
        this.aZ = false;
        this.bc = 0;
        this.bd = 0;
        this.be = 0;
        this.bf = null;
        this.bg = null;
        this.bh = null;
        this.bi = null;
        this.bj = null;
        this.bk = "";
        this.bp = null;
        this.bq = null;
        this.br = false;
        this.bs = null;
        this.bt = "";
        this.I = new d();
        this.q = new ArrayList(1);
        bb = new ArrayList(1);
        bm = false;
        bn = false;
        bo = false;
        aA = false;
        aB = false;
        this.bk = "";
    }

    public final String a() {
        String str = "1";
        return this.I != null ? (this.I.a == 2 || this.I.a == 3 || this.I.a == 5) ? "2" : str : str;
    }
}
